# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}    
    
    - name: Create .env file
      run: |
        touch .env
        echo 'REACT_APP_NEWS_API_KEY=${{ secrets.REACT_APP_NEWS_API_KEY }}' >> .env
        echo 'TOKEN=${{ secrets.TOKEN }}' >> .env
    
    - name: Install dependencies and run test
      run: |
        npm install 
        
