# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16.x]

    steps:
     - uses: actions/checkout@v2
     - name: Use Node.js ${{ matrix.node-version }}
       uses: actions/setup-node@v2
       with:
         node-version: ${{ matrix.node-version }}   
         cache: 'npm'
     - run: |
        npm cache clear --force
        tar czvf build.tar ./build      

     - name: Create .env file
        run:|
        touch .env
        echo 'REACT_APP_NEWS_API_KEY=${{ secrets.REACT_APP_NEWS_API_KEY }}' >> .env
        echo 'TOKEN=${{ secrets.TOKEN }}' >> .env
        
     - name: Upload build artifact
       uses: actions/upload-artifact@v3
       with:
         name: build
         path: build.tar
      
  deploy:
      name: Deploy build
      needs: build
      runs-on: self-hosted
      steps:
        - name: Download build
          uses: actions/download-artifact@v3
          with:
            name: build
        - run: tar xzvf build.tar
        
