# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs


name: CICD Frontend - React

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest  

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Create build
      run:  |
        npm install --legacy-peer-deps
        npm run build --if-present --verbose
        tar czvf build.tar ./build

    - name: Upload build
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: build.tar
    env:
     CI: false
 
  deploy:
    name: Deploy the build
    needs: build
    runs-on: self-hosted
    steps:
      - name: Create .env file
        run: |
          touch .env.production
          echo "REACT_APP_NEWS_API_KEY=${{ secrets.REACT_APP_NEWS_API_KEY }}" >> .env
          echo "TOKEN=${{ secrets.TOKEN }}" >> .env
          cat .env
    
      - name: Download the build
        uses: actions/download-artifact@v3
        with:
          name: build
      - run: tar xzvf build.tar
